[package]
name = "robot-dsl"
version = "0.1.0"
authors = ["yhteng <yhteng@bupt.edu.cn>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = "0.7.24"

[build-dependencies]
phf_codegen = "0.7.24"
